### ISSUE TITLE
Reason for inviting?

### ISSUE THREAD

**Issue by longrunningprocess** [jamiegamauf/smartsheet-php-client#1]
Hi Jamie, I received an invite from you on this one and just wanted to check in with you to make sure you don't need something from me.  Thanks.

**Comment by archofalltrades** [comment]
No, I don't need anything from you.  I saw that you started a PHP library
for Smartsheet awhile back.  I am trying to build one out myself and
thought you might be interested.

All the best,

*Jamie Gamauf, AIA, LEED AP*
http://jamie.daughausdev.com/portfolio/
https://www.linkedin.com/in/jamiegamauf/
301.275.7553

**Comment by longrunningprocess** [comment]
gotcha, have fun!  I wasn't involved directly, this is really https://github.com/fillup 's baby.
